apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vision-ai-yolox
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/explicitworkload/snuc-openshift-ai.git
    targetRevision: main
    path: vision-ai/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: visionai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
