apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: llamacpp
  namespace: john
  annotations:
    openshift.io/display-name: llamacpp
    security.opendatahub.io/enable-auth: "false"
    serving.kserve.io/deploymentMode: Standard
  labels:
    opendatahub.io/dashboard: "true"
spec:
  predictor:
    automountServiceAccountToken: false
    deploymentStrategy:
      type: RollingUpdate
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: gguf
      protocolVersion: v2
      resources:
        limits:
          amd.com/gpu: "1"
          cpu: "2"
          memory: 4Gi
        requests:
          amd.com/gpu: "1"
          cpu: "2"
          memory: 4Gi
      runtime: llamacpp
      storage:
        key: odf-s3
        path: /models/Llama-3.2-1B-Instruct-Q4_K_M.gguf