apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: llamacpp
  namespace: john
  annotations:
    opendatahub.io/recommended-accelerators: '["amd.com/gpu"]'
    opendatahub.io/runtime-version: (working)
    openshift.io/display-name: llama.cpp
  labels:
    opendatahub.io/dashboard: "true"
spec:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/path: /metrics
    opendatahub.io/kserve-runtime: "true"
  builtInAdapter:
    memBufferBytes: 134217728
    modelLoadingTimeoutMillis: 900000
  supportedModelFormats:
    - name: gguf
      autoSelect: true
  containers:
    - name: kserve-container
      image: quay.io/jgoh/llamacpp:latest
      imagePullPolicy: Always
      command:
        - /bin/sh
        - -c
        - >
          MODEL_FILE=$(find /mnt/models -type f -name "*.gguf" | head -n 1)

          if [ -z "$MODEL_FILE" ]; then
            echo "ERROR: No .gguf file found in /mnt/models"
            exit 1
          fi

          # Updated Flash Attention to '-fa off' for iGPU compatibility

          exec llama-server -m "$MODEL_FILE" --host 0.0.0.0 --port 8080 -fa off
          -ngl 99 --alias default
      ports:
        - containerPort: 8080
          name: http1
          protocol: TCP
      resources:
        requests:
          cpu: "4"
          memory: 8Gi
          amd.com/gpu: "1"
        limits:
          cpu: "8"
          memory: 16Gi
          amd.com/gpu: "1"
