apiVersion: v1
kind: Service
metadata:
  name: litellm-service
  labels:
    app: litellm-proxy
spec:
  selector:
    app: litellm-proxy
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: litellm-route
  annotations:
    haproxy.router.openshift.io/timeout: 300s
spec:
  to:
    kind: Service
    name: litellm-service
  port:
    targetPort: 4000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
