apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: vision-ai-build-
  namespace: visionai
spec:
  pipelineRef:
    name: vision-ai-build
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: vision-ai-build-source
    - name: registry-creds
      secret:
        secretName: quay-push-secret
