apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: vision-ai-build
  namespace: visionai
spec:
  params:
    - name: git-url
      type: string
      default: https://github.com/explicitworkload/llamacpp-oai.git
    - name: git-revision
      type: string
      default: experiment/vision-ai
    - name: serving-image
      type: string
      default: registry-quay-app.quay.svc.cluster.local/visionai/visionai:latest
    - name: app-image
      type: string
      default: registry-quay-app.quay.svc.cluster.local/visionai/visionai-app:latest
  workspaces:
    - name: source
    - name: registry-creds
  tasks:
    - name: clone
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
      params:
        - name: URL
          value: $(params.git-url)
        - name: REVISION
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: source

    - name: build-serving
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
      runAfter:
        - clone
      params:
        - name: IMAGE
          value: $(params.serving-image)
        - name: DOCKERFILE
          value: Dockerfile
        - name: TLS_VERIFY
          value: "false"
      workspaces:
        - name: source
          workspace: source
        - name: dockerconfig
          workspace: registry-creds

    - name: build-app
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
      runAfter:
        - clone
      params:
        - name: IMAGE
          value: $(params.app-image)
        - name: DOCKERFILE
          value: app/Dockerfile
        - name: TLS_VERIFY
          value: "false"
      workspaces:
        - name: source
          workspace: source
        - name: dockerconfig
          workspace: registry-creds
