apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vision-ai-build-source
  namespace: visionai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ocs-storagecluster-ceph-rbd
