apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vision-ai-pipelines
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/explicitworkload/llamacpp-oai.git
    targetRevision: experiment/vision-ai
    path: pipelines
  destination:
    server: https://kubernetes.default.svc
    namespace: visionai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
