apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: qwen35-4b-testing
  namespace: john
  annotations:
    openshift.io/display-name: qwen35-4b-testing
    security.opendatahub.io/enable-auth: "false"
    serving.kserve.io/deploymentMode: Standard
    serving.kserve.io/timeoutSeconds: "300"
  labels:
    opendatahub.io/dashboard: "true"
spec:
  predictor:
    automountServiceAccountToken: false
    deploymentStrategy:
      type: RollingUpdate
    maxReplicas: 1
    minReplicas: 1
    model:
      modelFormat:
        name: gguf
      protocolVersion: v2
      env:
        - name: CONTEXT_LENGTH
          value: "4096"
        - name: REASONING_BUDGET
          value: 0
      resources:
        limits:
          amd.com/gpu: "1"
          cpu: "6"
          memory: 32Gi
        requests:
          amd.com/gpu: "1"
          cpu: "4"
          memory: 16Gi
      runtime: llamacpp
      storage:
        key: models-odf-s3
        path: /models/Qwen_Qwen3.5-4B-Q4_K_M.gguf
