apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: llamacpp
  namespace: john
  annotations:
    opendatahub.io/recommended-accelerators: '["amd.com/gpu"]'
    opendatahub.io/runtime-version: (working)
    openshift.io/display-name: llama.cpp
  labels:
    opendatahub.io/dashboard: "true"
spec:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/path: /metrics
    opendatahub.io/kserve-runtime: "true"
  builtInAdapter:
    memBufferBytes: 134217728
    modelLoadingTimeoutMillis: 900000
  supportedModelFormats:
    - name: gguf
      autoSelect: true
  containers:
    - name: kserve-container
      image: quay.io/jgoh/llamacpp:latest
      imagePullPolicy: Always
      command:
        - /usr/local/bin/entrypoint.sh
      env:
        - name: CONTEXT_LENGTH
          value: "2048"
        - name: N_GPU_LAYERS
          value: "99"
        - name: REASONING_BUDGET
          value: "256"
        - name: FLASH_ATTENTION
          value: "on"
      ports:
        - containerPort: 8080
          name: http1
          protocol: TCP
      resources:
        requests:
          cpu: "4"
          memory: 8Gi
          amd.com/gpu: "1"
        limits:
          cpu: "8"
          memory: 16Gi
          amd.com/gpu: "1"
