apiVersion: v1
kind: Secret
metadata:
  name: quay-push-secret
  namespace: visionai
  annotations:
    tekton.dev/docker-0: https://registry-quay-app.quay.svc.cluster.local
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry-quay-app.quay.svc.cluster.local": {
          "auth": "<base64-encoded username:password>"
        }
      }
    }
