FROM registry.access.redhat.com/ubi9/python-312

USER 0

RUN dnf install -y --nodocs gcc python3-devel \
    && dnf clean all

USER 1001

RUN pip install --no-cache-dir onnxruntime kserve numpy

COPY serve.py /opt/serve.py

EXPOSE 8080

ENTRYPOINT ["python", "/opt/serve.py"]
